# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CNAME
- Gemfile
- Gemfile.lock

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: igor-drozdov # jekyll-seo-tag > Owners twitter username
author: igor-drozdov # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Igor Drozdov # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://github.com/igor-drozdov
    - https://www.linkedin.com/in/igor-drozdov-b58222102/
    - https://stackoverflow.com/users/2199600/igor-drozdov
    - https://twitter.com/rogiwodzard

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: "Igor Drozdov"
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text:
    feature_image: "/assets/cover.jpg"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/assets/cover.jpg" # Default image for sharing
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Igor Drozdov" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logo.png" # Site logo, also used in jekyll-seo-tag
description: "Igor Drozdov's personal blog" # Site description and default description, also used in jekyll-seo-tag
url: "https://ihar.me" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/igor-drozdov/igor-drozdov.github.io"
email: "ihar.drozdov@gmail.com"
disqus: "ihar-me" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "/assets/favicon.ico" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

# 8. Site navigation
navigation_header:

navigation_footer:

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  RSS: /feed.xml
  github: https://github.com/igor-drozdov
  linkedin: https://www.linkedin.com/in/igor-drozdov-b58222102/
  stackoverflow: https://stackoverflow.com/users/2199600/igor-drozdov
  gmail: mailto:ihar.drozdov@gmail.com
  twitter: https://twitter.com/rogiwodzard

google_analytics: "UA-107720992-1"

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#1DA1F2"
  facebook: "#3B5998"
  Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""
